#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:/bin
ifdown wlan0 --force --ignore-errors
ifup wlan0
iw dev wlan0 interface add uap0 type __ap
systemctl restart dnsmasq 
sysctl net.ipv4.ip_forward=1
iptables -t nat -A POSTROUTING -s 192.168.4.0/24 ! -d 192.168.4.0/24 -j MASQUERADE
ifdown uap0 --force  --ignore-errors
ifup uap0
#hostapd /etc/hostapd/hostapd.conf &
systemctl restart hostapd

