all:
	cd ThreadExecutors && make
	cd GpioIsr && make
	cd engines && make
	cd micro_calibrations && make
clean:
	cd ThreadExecutors && make clean
	cd GpioIsr && make clean
	cd engines && make clean
	cd micro_calibrations && make clean
	