all:
	cd loggers && make
	cd settings && make
	cd control_sensors && make
	cd control_engines && make
	cd grabber && make	
	cd droid && make
clean:
	cd loggers && make clean
	cd settings && make clean	
	cd control_sensors && make clean
	cd control_engines && make clean
	cd grabber && make clean
	cd droid && make clean
	